### ISSUE TITLE
0.7.0 broke my app

### ISSUE THREAD

**Issue by skortchmark9** [jarus/flask-testing#118] opened 2017-12-19 02:30 UTC
Hi there, we were running happily with 0.6.0 and the release of 0.7.0 broke my app. These tests used to work:
```
18-Dec-2017 16:48:58 | Traceback (most recent call last):
18-Dec-2017 16:48:58 | File "/vagrant/tests/test_api.py", line 21, in setUp
18-Dec-2017 16:48:58 | super(TestAPI, self).setUp()
18-Dec-2017 16:48:58 | File "/vagrant/tests/__init__.py", line 31, in setUp
18-Dec-2017 16:48:58 | db.drop_all()
18-Dec-2017 16:48:58 | File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 971, in drop_all
18-Dec-2017 16:48:58 | self._execute_for_all_tables(app, bind, 'drop_all')
18-Dec-2017 16:48:58 | File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 940, in _execute_for_all_tables
18-Dec-2017 16:48:58 | app = self.get_app(app)
18-Dec-2017 16:48:58 | File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 912, in get_app
18-Dec-2017 16:48:58 | 'No application found. Either work inside a view function or push'
18-Dec-2017 16:48:58 | RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```

**Comment by jcomo** [comment] 2017-12-19 17:30
Would you mind sharing the code (or making up an example) that reproduces the problem? We recently merged in #108 which put the control back on Flask for managing request contexts but as I noted in the PR, it may break compatibility for some users who were relying on the previously hacked behavior

**Comment by Syeberman** [comment] 2017-12-19 19:26
@jcomo Could you reply with a quick guide on how to establish a test request context the right way?  People are going to be thundering down upon this page pretty quickly.

**Comment by jcomo** [comment] 2017-12-19 19:31
The spirit of the fix was that you wouldn't have to do anything with the request context. It would be helpful to have an example of a test case that is failing to see what the problem is.

If it's affecting more people than it's helping, the best solution is to revert the change and try a different approach.

**Comment by jcomo** [comment] 2017-12-19 19:39
I think I see where the problem is coming in: when relying on the context to be implicitly available during setup/teardown methods. I'm going to revert the commit and save this change for a 1.0 release where it is more appropriate to change the behavior. I didn't it would have this much of a ripple effect.

0.7.1 will be released shortly and should fix the issue.

**Comment by jcomo** [comment] 2017-12-19 19:43
0.7.1 is now live on pypi. Apologies for the headaches this caused!

**Closed by jcomo** 2017-12-19 19:43 UTC

**Comment by Syeberman** [comment] 2017-12-19 19:53
We have a bunch of tests that don't go through the flask test client, but instead call certain functions directly that themselves require a request context.
